### ISSUE TITLE
Problem with converting weights to ONNX [URGENT]

### ISSUE THREAD

**Issue by jhl8041** [sw6y15/HKEvent#14] opened 2019-01-17 07:56 UTC
The conversion worked with tiny-yolo file but with while trying to convert our own trained cfg and weight

This error came up and I do not know how to deal with it.

already tried 
```
weights_header = np.ndarray(
        shape=(4, ), dtype='int32', buffer=weights_file.read(16))
```

here is the screen capture of error 
![image](https://user-images.githubusercontent.com/39699436/51303482-7306de00-1a70-11e9-9a51-a6b68e50218f.png)

**Comment by sw6y15** [comment] 2019-01-17 12:18
Sorry for late reply. What's your output before your change to read(16)? I think it should be right before your change 20 to 16

**Comment by wyh5625** [comment] 2019-01-17 12:25
We also have this problem

**Comment by sw6y15** [comment] 2019-01-17 13:13
Thank you for your reporting. I saw your Darknet weights size is large. Maybe you both use the deeper version model, which might cause the quesion. I've tried convert yolov2 and yolov3 to Keras. It needs to modify several places in the yad2k.py. However, in the last step convert it to coreml or ONNX, cuz some layers in those models are not supported, so I am afraid you should use tiny-yolo that I recommand on the slides.

**Comment by jhl8041** [comment] 2019-01-17 13:23
> so I am afraid you should use tiny-yolo that I recommand on the slides.

What you do mean by use tiny-yolo?

So does it mean we cannot use our trained weight file to convert to ONNX???

**Comment by jhl8041** [comment] 2019-01-17 16:09
Which part of yad2k.py should we change to make [reorg] [route] readable?? Please answer me  ASAP

**Comment by sw6y15** [comment] 2019-01-18 02:28
Duplicate of #16 
For converting it to only keras format, you can refer to [this](https://github.com/allanzelener/YAD2K).
However, I am sure it cannot convert to ONNX until now.

**Closed as completed** 2019-01-19 18:29 UTC
